### ISSUE TITLE
No support to preview mjml files generated by other tools

### ISSUE THREAD

**Issue by SteakOvercooked** [mjmlio/vscode-mjml#41]
## Expected behavior

Having the ability to preview any mjml file in webview

## Actual behavior

The current active document is rendered into webview

## The problem

If i use any templating language (EJS, Pug, Handlebars, etc.) i can not preview the document i am working on because their syntax is not supported by mjml. I have no ability to view changes live and i need to switch to the tab with the result of processing _each time_ i want to check on the output.

## Suggested solution

Use something like [FileSystemWatcher](https://code.visualstudio.com/api/references/vscode-api#3178) to track changes made to templating language output and update webview accordingly, allowing to view live changes to mjml files generated by other tools.

**Comment by iRyusa** [comment]
Hi,

This is out of the scope of this extension here so we won't do anything
about this.

**Comment by SteakOvercooked** [comment]
Would you review a PR if i made one?

**Comment by ivank** [comment]
After reading https://thoughtbot.com/blog/building-templated-emails-with-mjml I figured the vscode extension _should_ be able to do this! Turns out no, you can't switch to the `.mjmlconfig.js` file in order to use preprocessors.

I created a PR to fix this in this extension https://github.com/mjmlio/vscode-mjml/pull/47 but while we wait for them to approve / merge it, I've deployed my own forked version https://marketplace.visualstudio.com/items?itemName=IvanKeirn.vscode-mjml-custom-path 

We're using that in order to preview files with handlebars templates - it's quite nice!

**Comment by iRyusa** [comment]
Yeah preprocessors should help :+1:
